# BID COIN asset
[[CURRENCIES]]
code="BID"
issuer="GCQDHQHWJTK6KPBVVNZRO5EYN6BLUFGHVY6XE4YYD566WQPVWWM5TYGT"
display_decimals=2 
name="BID Coin"
desc="1 bid coin allows you to bid, recieve others bid, and accept winning bids; BID Coin can/may serve auctions on and offline."
conditions="Private round ICO is Nov 2nd, 2018 through Nov 21, 2018 and is open to accredited investors. Public ICO Nov 22nd 2018, through Dec 21st, 2018."
image="https://107.180.48.113:2083/cpsess2135808783/frontend/gl_paper_lantern/filemanager/showfile.html?file=BIDcoin+logo+lg.png&fileop=&dir=%2Fhome%2Fxs8m3ansg9ba%2Fpublic_html&dirop=&charset=&file_charset=&baseurl=&basedir="

